version: '3.9'

services:
  alloy:
    image: grafana/alloy:latest
    user: "10001:0"
    command: ["run", "--storage.path=/alloy-data", "/etc/alloy/config.alloy"]
    environment:
      - ALLOY_DEPLOY_MODE=docker
    networks:
      - traefik-public
    volumes:
      - ${HOME}/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ${HOME}/alloy/data:/alloy-data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      labels:
        - traefik.enable=false
networks:
  traefik-public:
    external: true