version: '3.9'

services:
  etherpad:
    image: etherpad/etherpad:latest
    networks:
      - traefik-public
    environment:
      NODE_ENV: production
      DB_TYPE: ${ETHERPAD_DB_TYPE}
      DB_HOST: ${ETHERPAD_DB_HOST}
      DB_PORT: ${ETHERPAD_DB_PORT}
      DB_USER: ${ETHERPAD_DB_USER}
      DB_PASS: ${ETHERPAD_DB_PASS}
      DB_NAME: ${ETHERPAD_DB_NAME}
      TRUST_PROXY: ${ETHERPAD_TRUST_PROXY}
      ADMIN_PASSWORD: ${ETHERPAD_ADMIN_PASSWORD}
    volumes:
      - ${HOME}/etherpad/plugins:/opt/etherpad-lite/src/plugin_packages
      - ${HOME}/etherpad/var:/opt/etherpad-lite/var
      - ${HOME}/etherpad/settings.json:/opt/etherpad-lite/settings.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.etherpad.rule=Host(`${ETHERPAD_HOSTNAME}`)
        - traefik.http.routers.etherpad.entrypoints=https
        - traefik.http.routers.etherpad.service=etherpad
        - traefik.http.routers.etherpad.tls.certresolver=mydnschallenge
        - traefik.http.services.etherpad.loadbalancer.server.port=9001
        - traefik.http.routers.etherpad.middlewares=my-keycloakopenid

networks:
  traefik-public:
    external: true
