version: '3.9'

services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - traefik-public
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ${HOME}/grafana:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOSTNAME}`)
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.entrypoints=https
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver=mydnschallenge

networks:
  traefik-public:
    external: true