version: '3.9'

services:
  invoiceninja:
    image: invoiceninja/invoiceninja-debian:5
    networks:
      - traefik-invoiceninja
    volumes:
      - ${HOME}/invoiceninja/public:/var/www/html/public
      - ${HOME}/invoiceninja/storage:/var/www/html/storage
      - ${HOME}/invoiceninja/php/php.ini:/usr/local/etc/php/conf.d/invoiceninja.ini:ro
      - ${HOME}/invoiceninja/php/php-fpm.conf:/usr/local/etc/php-fpm.d/invoiceninja.conf:ro
      - ${HOME}/invoiceninja/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    environment:
      APP_URL: https://${INVOICENINJA_HOSTNAME}
      APP_KEY: ${INVOICENINJA_APP_KEY}
      APP_ENV: production
      APP_DEBUG: "false"
      REQUIRE_HTTPS: "true"
      PHANTOMJS_PDF_GENERATION: "false"
      PDF_GENERATOR: snappdf
      TRUSTED_PROXIES: '*'
      DB_HOST: invoiceninja-mariadb
      DB_PORT: ${INVOICENINJA_MARIADB_PORT}
      DB_DATABASE: ${INVOICENINJA_MARIADB_DATABASE}
      DB_USERNAME: ${INVOICENINJA_MARIADB_USER}
      DB_PASSWORD: ${INVOICENINJA_MARIADB_PASSWORD}
      IN_USER_EMAIL: ${INVOICENINJA_IN_USER_EMAIL}
      IN_PASSWORD: ${INVOICENINJA_IN_PASSWORD}
      MAIL_MAILER: smtp
      MAIL_HOST: ${INVOICENINJA_MAIL_HOST}
      MAIL_PORT: ${INVOICENINJA_MAIL_PORT}
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: ${INVOICENINJA_MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: 'Invoice Ninja'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=false

  invoiceninja-mariadb:
    image: mariadb:11.8.2
    networks:
      - traefik-invoiceninja
    environment:
      MARIADB_ROOT_PASSWORD: ${INVOICENINJA_MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${INVOICENINJA_MARIADB_DATABASE}
      MARIADB_USER: ${INVOICENINJA_MARIADB_USER}
      MARIADB_PASSWORD: ${INVOICENINJA_MARIADB_PASSWORD}
    volumes:
      - invoiceninja-mariadb-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=false

  invoiceninja-nginx:
    image: nginx:latest
    volumes:
      - ${HOME}/invoiceninja/nginx:/etc/nginx/conf.d:ro
      - ${HOME}/invoiceninja/public:/var/www/html/public:ro
      - ${HOME}/invoiceninja/storage:/var/www/html/storage:ro
    networks:
      - traefik-public
      - traefik-invoiceninja
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.invoiceninja.rule=Host(`${INVOICENINJA_HOSTNAME}`)
        - traefik.http.routers.invoiceninja.entrypoints=https
        - traefik.http.routers.invoiceninja.service=invoiceninja
        - traefik.http.routers.invoiceninja.tls.certresolver=mydnschallenge
        - traefik.http.services.invoiceninja.loadbalancer.server.port=80

  invoiceninja-redis:
    image: redis:8.0.3
    networks:
      - traefik-invoiceninja
    volumes:
      - ${HOME}/invoiceninja/redis:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=false
    
volumes:
  invoiceninja-mariadb-data:

networks:
  traefik-public:
    external: true
  traefik-invoiceninja:
    driver: overlay
