version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    networks:
      - traefik-public
      - traefik-jenkins
    privileged: true
    user: root
    volumes:
      - ${HOME}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.http.routers.jenkins.rule=Host(`${JENKINS_HOSTNAME}`)
        - traefik.http.services.jenkins.loadbalancer.server.port=8080
        - traefik.http.routers.jenkins.entrypoints=https
        - traefik.http.routers.jenkins.tls=true
        - traefik.http.routers.jenkins.tls.certresolver=mydnschallenge

  agent:
    image: jenkins/ssh-agent:jdk21
    networks:
      - traefik-jenkins
    privileged: true
    user: root
    expose:
      - 22
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "${JENKINS_AGENT_SSH_TYPE} ${JENKINS_AGENT_SSH_KEY} ${JENKINS_AGENT_SSH_USER}"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.enable=false

networks:
  traefik-public:
    external: true
  traefik-jenkins:
    driver: overlay
