version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    networks:
      - traefik-public
    environment:
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KEYCLOAK_ADMIN=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_LOG_LEVEL=info
      - KC_HEALTH_ENABLED=false
      - KC_METRICS_ENABLED=false
      - KC_DB=${KC_DB_TYPE}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    command: ["start", "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.http.routers.keycloak.rule=Host(`${KC_HOSTNAME}`)
        - traefik.http.services.keycloak.loadbalancer.server.port=8080
        - traefik.http.routers.keycloak.entrypoints=https
        - traefik.http.routers.keycloak.tls=true
        - traefik.http.routers.keycloak.tls.certresolver=mydnschallenge
        - traefik.http.routers.keycloak.middlewares=gzip

networks:
  traefik-public:
    external: true
