version: '3.9'

services:
  listmonk:
    image: listmonk/listmonk:latest
    networks:
      - traefik-public
    hostname: ${LISTMONK_FQDN}
    environment:
      TZ: "US/Eastern"
      LISTMONK_app__address: ${LISTMONK_ADDRESS}
      LISTMONK_db__host: ${LISTMONK_DB_HOST}
      LISTMONK_db__port: ${LISTMONK_DB_PORT}
      LISTMONK_db__user: ${LISTMONK_DB_USER}
      LISTMONK_db__password: ${LISTMONK_DB_PASSWORD}
      LISTMONK_db__database: ${LISTMONK_DB_NAME}
      LISTMONK_db__ssl_mode: require
      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s
    volumes:
      - ${HOME}/listmonk/uploads:/listmonk/uploads
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.enable=true
        # change the host here
        - traefik.http.routers.listmonk.rule=Host(`${LISTMONK_FQDN}`)
        - traefik.http.services.listmonk.loadbalancer.server.port=9000
        - traefik.http.routers.listmonk.entrypoints=https
        - traefik.http.routers.listmonk.tls=true
        - traefik.http.routers.listmonk.tls.certresolver=mydnschallenge
        - traefik.http.routers.listmonk.middlewares=gzip
    command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]

networks:
  traefik-public:
    external: true
