version: '3.9'

services:
  loki:
    image: grafana/loki:latest
    networks:
      - traefik-public
    volumes:
      - ${HOME}/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - ${HOME}/loki/data:/loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"
      - "-auth.enabled=false"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == ${STACK_PARAM}
      labels:
        - traefik.http.routers.loki.rule=Host(`${LOKI_HOSTNAME}`)
        - traefik.http.services.loki.loadbalancer.server.port=3100
        - traefik.http.routers.loki.entrypoints=${TRAEFIK_ENTRYPOINT}
        - traefik.http.routers.loki.tls=${TRAEFIK_TLS_ENABLED}
        - traefik.http.routers.loki.tls.certresolver=mydnschallenge

networks:
  traefik-public:
    external: true
