version: '3.9'

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
    networks:
      - traefik-public
    volumes:
      - ${HOME}/mailhog/maildir:/maildir
      - ${HOME}/mailhog/outgoing_smtp.json:/outgoing_smtp.json
    environment:
      MH_HOSTNAME: ${MH_ROOT_DOMAIN}
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /maildir
      MH_OUTGOING_SMTP: /outgoing_smtp.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Change the host here
        - traefik.http.routers.mailhog.rule=Host(`${MAILHOG_HOSTNAME}`)
        - traefik.http.services.mailhog.loadbalancer.server.port=8025
        - traefik.http.routers.mailhog.entrypoints=https
        - traefik.http.routers.mailhog.service=mailhog
        - traefik.http.routers.mailhog.tls.certresolver=mydnschallenge
        - traefik.http.routers.mailhog.middlewares=gzip,my-keycloakopenid

networks:
  traefik-public:
    external: true
