version: '3.9'

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
        - traefik-public
    volumes:
      - ${HOME}/mailhog/maildir:/maildir
      - ${HOME}/mailhog/outgoing_smtp.json:/outgoing_smtp.json
    environment:
      MH_HOSTNAME: pimaker.org
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /maildir
      MH_OUTGOING_SMTP: /outgoing_smtp.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == traefikapp
      labels:
        - traefik.enable=true
        # change the host here
        - traefik.http.routers.mailhog.rule=Host(`mailhog.pimaker.org`)
        - traefik.http.services.mailhog.loadbalancer.server.port=8025
        - traefik.http.routers.mailhog.entrypoints=websecure
        - traefik.http.routers.mailhog.tls=true
        - traefik.http.routers.mailhog.tls.certresolver=mydnschallenge
        - traefik.http.routers.mailhog.middlewares=gzip,authmailhog
        # Change the auth password here
        - traefik.http.middlewares.authmailhog.basicauth.users=admin:$$2y$$05$$hGP72w.Rgky4RK7FrN9km.UpdwwHqB8gJNp8TQ4s4qDK8LxjfISl6"

networks:
  traefik-public:
    external: true