version: '3.9'

services:
  matomo:
    image: matomo:latest
    depends_on:
      - matomo-db
    networks:
      - traefik-public
      - traefik-matomo
    ports:
      - 9000:80
    volumes:
      - ${HOME}/matomo/config:/var/www/html/config:rw
      - ${HOME}/matomo/logs:/var/www/html/logs
      - ${HOME}/matomo/php.ini:/usr/local/etc/php/php.ini
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == traefikapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # SERVICES: Main
        - traefik.http.services.matomo.loadbalancer.server.port=80
        # HOSTS: Main
        - traefik.http.routers.matomo.rule=(Host(`stats.pimaker.org`) || Host(`stats.lillymountain.com`) || Host(`stats.happybaseball.com`))
        - traefik.http.routers.matomo.entrypoints=websecure
        - traefik.http.routers.matomo.tls=true
        - traefik.http.routers.matomo.tls.certresolver=mydnschallenge
        - traefik.http.routers.matomo.service=matomo
        - traefik.http.routers.matomo.middlewares=gzip

  matomo-db:
    image: mariadb:10.11.5
    networks:
      - traefik-matomo
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATBASE: ${MARIADB_DATBASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - matomo-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == traefikapp
      labels:
        - traefik.enable=true
        - traefik.http.services.justAdummyService.loadbalancer.server.port=1337
        - traefik.http.routers.traefikRouter.rule=Host(`127.0.0.11`)
        - traefik.http.routers.traefikRouter.service=api@internal
        - traefik.http.routers.traefikRouter.entrypoints=web

volumes:
  matomo-data:

networks:
  traefik-public:
    external: true
  traefik-matomo:
    driver: overlay
