version: '3.9'
configs:
  netdata_stream_master:
    file: $PWD/stream-master.conf
  netdata_stream_client:
    file: $PWD/stream-client.conf
services:
  netdata-client:
    image: netdata/netdata:v2.0.0
    hostname: "{{.Node.Hostname}}-{{.Node.ID}}-{{.Service.Name}}"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - netdata-central
    configs:
        -
          mode: 444
          source: netdata_stream_client
          target: /etc/netdata/stream.conf
    networks:
      - netdata
    environment:
      - PGID=999
    volumes:
      - ./msmtprc:/etc/msmtprc
      - ./health_alarm_notify.conf:/etc/health_alarm_notify.conf
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
        - node.platform.os == linux
        - node.labels.type != traefikapp

  netdata-central:
    image: netdata/netdata:v2.0.0
    hostname: control
    configs:
      -
        mode: 444
        source: netdata_stream_master
        target: /etc/netdata/stream.conf
    networks:
      - netdata
      - traefik-public
    environment:
      - PGID=999
    volumes:
      - ./msmtprc:/etc/msmtprc
      - ./health_alarm_notify.conf:/etc/health_alarm_notify.conf
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == traefikapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.netdata.rule=Host(`netdata.pimaker.org`)
        - traefik.http.routers.netdata.entrypoints=https
        - traefik.http.routers.netdata.tls.certresolver=mydnschallenge
        - traefik.http.services.web.loadbalancer.server.port=19999
        - traefik.http.routers.netdata.middlewares=netdata-auth
        # Change the auth password here
        - traefik.http.middlewares.netdata-auth.basicauth.users=admin:${TRAEFIK_HASHED_PASSWORD}

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  traefik-public:
    external: true
  netdata:
    driver: overlay
    attachable: true