version: '3.9'

services:
  nginx1:
    image: nginx:latest
    networks:
      - traefik-public
    volumes:
      - ${HOME}/nginx1/html:/usr/share/nginx/html
      - ${HOME}/nginx1/logs:/var/log/nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.nginx1.rule=Host(`${NGINX_1_HOSTNAME}`)
        - traefik.http.services.nginx1.loadbalancer.server.port=80
        - traefik.http.routers.nginx1.entrypoints=https
        - traefik.http.routers.nginx1.tls=true
        - traefik.http.routers.nginx1.tls.certresolver=mydnschallenge

  nginx2:
    image: nginx:latest
    networks:
      - traefik-public
    volumes:
      - ${HOME}/nginx2/html:/usr/share/nginx/html
      - ${HOME}/nginx2/logs:/var/log/nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.nginx2.rule=Host(`${NGINX_2_HOSTNAME}`)
        - traefik.http.services.nginx2.loadbalancer.server.port=80
        - traefik.http.routers.nginx2.entrypoints=https
        - traefik.http.routers.nginx2.tls=true
        - traefik.http.routers.nginx2.tls.certresolver=mydnschallenge
        - traefik.http.routers.nginx2.middlewares=my-keycloakopenid

networks:
  traefik-public:
    external: true
