version: '3.9'

services:
  mail:
    image: boky/postfix
    ports:
      - $POSTFIX_PORT:587
    volumes:
      - ${HOME}/postfix/dkim-keys:/etc/opendkim/keys
    networks:
      - traefik-public
    environment:
      - POSTFIX_myhostname=${POSTFIX_HOSTNAME}
      - ALLOWED_SENDER_DOMAINS=${POSTFIX_ALLOWED_SENDER_DOMAINS}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.enable=true
        - traefik.http.services.justAdummyService.loadbalancer.server.port=1337
        - traefik.http.routers.traefikRouter.rule=Host(`127.0.0.11`)
        - traefik.http.routers.traefikRouter.service=api@internal
        - traefik.http.routers.traefikRouter.entrypoints=http

networks:
  traefik-public:
    external: true