version: '3.9'

services:
  mail:
    image: bytemark/smtp
    networks:
        - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == traefikapp

networks:
  traefik-public:
    external: true