version: '3'

services:
  snipe-it:
    image: snipe/snipe-it:v8-latest
    networks:
      - traefik-public
      - traefik-snipe-it
    environment:
      TZ: ${SNIPEIT_TZ}
      APP_URL: https://${SNIPEIT_HOSTNAME}
      APP_KEY: ${SNIPEIT_APP_KEY}
      APP_TRUSTED_PROXIES: ${SNIPEIT_APP_TRUSTED_PROXIES}
      APP_FORCE_TLS: 'true'
      DB_HOST: snipe-it-mariadb
      DB_PORT: ${SNIPEIT_MARIADB_PORT}
      DB_DATABASE: ${SNIPEIT_MARIADB_DATABASE}
      DB_USERNAME: ${SNIPEIT_MARIADB_USER}
      DB_PASSWORD: ${SNIPEIT_MARIADB_PASSWORD}
      MAIL_MAILER: smtp
      MAIL_HOST: ${SNIPEIT_MAIL_HOST}
      MAIL_PORT: ${SNIPEIT_MAIL_PORT}
      MAIL_FROM_ADDR: ${SNIPEIT_MAIL_FROM_ADDR}
      MAIL_FROM_NAME: 'Snipe-IT'
      MAIL_REPLYTO_ADDR: ${SNIPEIT_MAIL_FROM_ADDR}
      MAIL_REPLYTO_NAME: 'Snipe-IT'
    volumes:
      - ${HOME}/snipe-it/storage:/var/lib/snipeit
      - ${HOME}/snipe-it/logs:/var/www/html/storage/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.snipeit.rule=Host(`${SNIPEIT_HOSTNAME}`)
        - traefik.http.services.snipeit.loadbalancer.server.port=80
        - traefik.http.routers.snipeit.entrypoints=https
        - traefik.http.routers.snipeit.tls=true
        - traefik.http.routers.snipeit.tls.certresolver=mydnschallenge
        - traefik.http.routers.snipeit.middlewares=add-x-forwarded-header
    command: [sh, -c, "echo 'Sleep for 10 sec to wait for mariadb to come up...' && sleep 10 && /startup.sh"]

  snipe-it-mariadb:
    image: mariadb:12.1.2
    networks:
      - traefik-snipe-it
    environment:
      TZ: ${SNIPEIT_TZ}
      MARIADB_ROOT_PASSWORD: ${SNIPEIT_MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${SNIPEIT_MARIADB_DATABASE}
      MARIADB_USER: ${SNIPEIT_MARIADB_USER}
      MARIADB_PASSWORD: ${SNIPEIT_MARIADB_PASSWORD}
    volumes:
      - snipe-it-mariadb-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=false

volumes:
  snipe-it-mariadb-data:

networks:
  traefik-public:
    external: true
  traefik-snipe-it:
    driver: overlay