version: '3.9'

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    networks:
      - tailscale-public
    ports:
      - ${STIRLING_EXTERNAL_PORT}:${STIRLING_SERVER_PORT}
    environment:
      - SERVER_PORT=${STIRLING_SERVER_PORT}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == ${STACK_PARAM}
      labels:
        - traefik.enable=false
        - tsdproxy.enable=true
        - tsdproxy.name=pdf
        - tsdproxy.port.1=${STIRLING_SERVER_PORT}/http->http://${STIRLING_PDF_HOSTNAME}:${STIRLING_EXTERNAL_PORT}
        - tsdproxy.scheme=http
        - tsdproxy.tlsvalidate=false
        - tsdproxy.ephemeral=true
        - tsdproxy.autodetect=false
    healthcheck:
      test: ["CMD-SHELL", "curl -fs --max-time 10 http://localhost:${STIRLING_SERVER_PORT}${SYSTEM_ROOTURIPATH:-''}/api/v1/info/status || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 5

networks:
  tailscale-public:
    external: true