version: '3.9'

services:
  tailscale:
    image: tailscale/tailscale:stable
    hostname: tailscale-happy
    networks:
      - traefik-tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS1} ${TS_EXTRA_ARGS2} ${TS_EXTRA_ARGS3}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${HOME}/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=false

networks:
  traefik-tailscale:
    driver: overlay
