version: '3.9'

services:
  traefik:
    image: traefik:v3.5.0-rc1
    command:
      - --log.level=INFO
      - --log.filePath=/var/log/traefik/traefik.log
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.middlewares=gzip
      - --providers.swarm=true
      - --providers.swarm.watch=true
      - --providers.swarm.network=traefik-public
      - --api
      - --api.dashboard=true
      # Plugins
      - --experimental.plugins.keycloakopenid.moduleName=github.com/bcambl/keycloakopenid
      - --experimental.plugins.keycloakopenid.version=v0.1.47
      # DNS Resolver
      - --certificatesresolvers.mydnschallenge.acme.dnschallenge=true
      - --certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=linodev4
      - --certificatesresolvers.mydnschallenge.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.mydnschallenge.acme.storage=/le/acme.json
      # Enable the access log, with HTTP requests
      - --accesslog.bufferingsize=100
      - --accesslog.filepath=/var/log/traefik/traefik-access.log
      # keep headers and user agents in logs
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.names.ClientUsername=drop
      - --accesslog.fields.headers.defaultmode=keep
      - --accesslog.fields.headers.names.User-Agent=keep
      - --accesslog.fields.headers.names.Authorization=drop
      - --accesslog.fields.headers.names.Content-Type=keep
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - traefik-public
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
      LINODE_TOKEN: ${LINODE_TOKEN}
      TRAEFIK_KEYCLOAK_URL: ${TRAEFIK_KEYCLOAK_URL}
      TRAEFIK_KEYCLOAK_CLIENT_ID: ${TRAEFIK_KEYCLOAK_CLIENT_ID}
      TRAEFIK_KEYCLOAK_CLIENT_SECRET: ${TRAEFIK_KEYCLOAK_CLIENT_SECRET}
      TRAEFIK_KEYCLOAK_REALM: ${TRAEFIK_KEYCLOAK_REALM}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Make sure the volume folder is created
      - ${HOME}/traefik/data/acme.json:/le/acme.json
      - ${HOME}/traefik/logs/:/var/log/traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == traefikapp
      labels:
        # Dashboard
        - traefik.enable=true
        # Change the host url here
        - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOSTNAME}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.tls.certresolver=mydnschallenge
        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.middlewares=my-keycloakopenid

        # GENERIC MIDDLEWARES
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.middlewares.gzip.compress=true
        - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png,image/jpeg,font/woff2

        # KEYCLOAK MIDDLEWARE
        - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.KeycloakURLEnv=TRAEFIK_KEYCLOAK_URL
        - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.InsecureSkipVerify=false
        - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.ClientIDEnv=TRAEFIK_KEYCLOAK_CLIENT_ID
        - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.ClientSecretEnv=TRAEFIK_KEYCLOAK_CLIENT_SECRET
        - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.KeycloakRealmEnv=TRAEFIK_KEYCLOAK_REALM
        - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.Scope=openid
        - traefik.http.middlewares.my-keycloakopenid.plugin.keycloakopenid.UseAuthHeader=false

        # GENERIC ROUTERS
        - traefik.http.routers.generic-https-redirect.entrypoints=http
        - traefik.http.routers.generic-https-redirect.rule=HostRegexp(`.*`)
        - traefik.http.routers.generic-https-redirect.priority=1
        - traefik.http.routers.generic-https-redirect.middlewares=https-redirect

networks:
  traefik-public:
    external: true
