version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    networks:
      - traefik-public
    volumes:
      - ${HOME}/vaultwarden/data/:/data/
    environment:
      - DATABASE_URL=${VAULTWARDEN_DATABASE_URL}
      - DOMAIN=https://${VAULTWARDEN_HOSTNAME}
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=${VAULTWARDEN_SMTP_HOST}
      - SMTP_FROM=${VAULTWARDEN_SMTP_FROM}
      - SMTP_FROM_NAME=${VAULTWARDEN_SMTP_FROM_NAME}
      - SMTP_SECURITY=${VAULTWARDEN_SMTP_SECURITY}
      - SMTP_PORT=${VAULTWARDEN_SMTP_PORT}
      - SMTP_AUTH_MECHANISM=${VAULTWARDEN_SMTP_AUTH_MECHANISM}
#      - SSO_ENABLED=${VAULTWARDEN_SSO_ENABLED}	 # Set to true to enable OIDC functionality.
#      - SSO_AUTHORITY=${VAULTWARDEN_SSO_AUTHORITY}	 # URL of the OIDC provider (e.g., your IdP).
#      - SSO_CLIENT_ID=${VAULTWARDEN_SSO_CLIENT_ID}	 # Unique identifier for the OIDC client.
#      - SSO_CLIENT_SECRET=${VAULTWARDEN_SSO_CLIENT_SECRET}	 # Secret used to authenticate the client with the IdP.
#      - SSO_SCOPES=${VAULTWARDEN_SSO_SCOPES}	 # Scopes required for the OIDC authentication.
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.vaultwarden.rule=Host(`${VAULTWARDEN_HOSTNAME}`)
        - traefik.http.services.vaultwarden.loadbalancer.server.port=80
        - traefik.http.routers.vaultwarden.entrypoints=https
        - traefik.http.routers.vaultwarden.tls=true
        - traefik.http.routers.vaultwarden.tls.certresolver=mydnschallenge

networks:
  traefik-public:
    external: true
